language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-30.0.0
    - android-30

before_install:
  - yes | sdkmanager "platforms;android-30"
  - chmod +x gradlew

script:
    - ./gradlew clean build
    - ./gradlew assembleDebug
    - ./gradlew test
    
