name: Testing Workflow

on:
  pull_request:
    branches:
      - dev
      - test
      - main
  push:
    branches:
      - dev
      - test
      - main

jobs:
    testing:
      name: Lint Check and Unit Testing

      runs-on: ubuntu-latest

      steps:
        - name: Clone Repo
          uses: actions/checkout@v1

        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8

        # Give permission to gradle
        - name: Give permission to gradle
          run: chmod +x gradlew
          
        # Check the code with ktlint
        #- name: Run Kotlin Linter
        #  run: ./gradlew ktlintStagingDebugCheck

        # Check the code with Android linter
        #- name: Run Android Linter
        #  run: ./gradlew lintStagingDebug

        # Run your unit tests
        #- name: Run Unit Tests
        #  run: ./gradlew testStagingDebugUnitTest
        
        # Run your unit tests
        - name: Run Unit Tests
          run: ./gradlew test
          
        # Step 4: Assemble debug test apk to send to firebase test lab
        #- name: Assemble Debug Test APK
        #  run: ./gradlew assembleStagingDebugAndroidTest  
